"""empty message

Revision ID: 8657c63989d3
Revises: 
Create Date: 2023-03-18 10:28:25.819670

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8657c63989d3'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('bookmark',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('mname', sa.String(length=256), nullable=True),
    sa.Column('link', sa.String(length=512), nullable=True),
    sa.Column('chapter', sa.DECIMAL(precision=20, scale=2), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('bookmark', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_bookmark_link'), ['link'], unique=True)
        batch_op.create_index(batch_op.f('ix_bookmark_mname'), ['mname'], unique=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('bookmark', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_bookmark_mname'))
        batch_op.drop_index(batch_op.f('ix_bookmark_link'))

    op.drop_table('bookmark')
    # ### end Alembic commands ###
